=begin
#Kinde Management API

# Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::BillingAgreementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingAgreementsApi' do
  before do
    # run before each test
    @api_instance = KindeApi::BillingAgreementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingAgreementsApi' do
    it 'should create an instance of BillingAgreementsApi' do
      expect(@api_instance).to be_instance_of(KindeApi::BillingAgreementsApi)
    end
  end

  # unit tests for create_billing_agreement
  # Creates a new billing agreement based on the plan code passed, and cancels the customer&#39;s existing agreements  &lt;div&gt;   &lt;code&gt;create:billing_agreements&lt;/code&gt; &lt;/div&gt; 
  # @param create_billing_agreement_request New agreement request values
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'create_billing_agreement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_billing_agreements
  # Get billing agreements
  # Returns all the agreements a billing customer currently has access to  &lt;div&gt;   &lt;code&gt;read:billing_agreements&lt;/code&gt; &lt;/div&gt; 
  # @param customer_id The ID of the billing customer to retrieve agreements for
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Number of results per page. Defaults to 10 if parameter not sent.
  # @option opts [String] :starting_after The ID of the billing agreement to start after.
  # @option opts [String] :ending_before The ID of the billing agreement to end before.
  # @option opts [String] :feature_code The feature code to filter by agreements only containing that feature
  # @return [GetBillingAgreementsResponse]
  describe 'get_billing_agreements test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
