=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::CallbacksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallbacksApi' do
  before do
    # run before each test
    @api_instance = KindeApi::CallbacksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallbacksApi' do
    it 'should create an instance of CallbacksApi' do
      expect(@api_instance).to be_instance_of(KindeApi::CallbacksApi)
    end
  end

  # unit tests for add_redirect_callback_urls
  # Add Redirect Callback URLs
  # Add additional redirect callback URLs. 
  # @param app_id The identifier for the application.
  # @param urls Array of callback urls.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_redirect_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_callback_urls
  # List Callback URLs
  # Returns an application&#39;s redirect callback URLs. 
  # @param app_id The identifier for the application.
  # @param [Hash] opts the optional parameters
  # @return [GetRedirectCallbackUrlsResponse]
  describe 'get_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_redirect_callback_urls
  # Replace redirect callback URLs
  # Replace all redirect callback URLs. 
  # @param app_id The identifier for the application.
  # @param urls Array of callback urls.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'replace_redirect_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
