# frozen_string_literal: true

# #Kinde Management API
#
# Provides endpoints to manage your Kinde Businesses
#
# The version of the OpenAPI document: 1
# Contact: support@kinde.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.0.0-SNAPSHOT
#

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::CallbacksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CallbacksApi' do
  before do
    # run before each test
    @api_instance = KindeApi::CallbacksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallbacksApi' do
    it 'should create an instance of CallbacksApi' do
      expect(@api_instance).to be_instance_of(KindeApi::CallbacksApi)
    end
  end

  # unit tests for add_logout_redirect_urls
  # Add Logout Redirect URLs
  # Add additional logout redirect URLs.
  # @param app_id The identifier for the application.
  # @param replace_logout_redirect_urls_request Callback details.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'add_logout_redirect_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_redirect_callback_urls
  # Add Redirect Callback URLs
  # Add additional redirect callback URLs.
  # @param app_id The identifier for the application.
  # @param replace_redirect_callback_urls_request Callback details.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'add_redirect_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_callback_urls
  # Delete Callback URLs
  # Delete callback URLs.
  # @param app_id The identifier for the application.
  # @param urls Urls to delete, comma separated and url encoded.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'delete_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_logout_urls
  # Delete Logout URLs
  # Delete logout URLs.
  # @param app_id The identifier for the application.
  # @param urls Urls to delete, comma separated and url encoded.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'delete_logout_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_callback_urls
  # List Callback URLs
  # Returns an application&#39;s redirect callback URLs.
  # @param app_id The identifier for the application.
  # @param [Hash] opts the optional parameters
  # @return [RedirectCallbackUrls]
  describe 'get_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_logout_urls
  # List Logout URLs
  # Returns an application&#39;s logout redirect URLs.
  # @param app_id The identifier for the application.
  # @param [Hash] opts the optional parameters
  # @return [LogoutRedirectUrls]
  describe 'get_logout_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replace_logout_redirect_urls
  # Replace Logout Redirect URLs
  # Replace all logout redirect URLs.
  # @param app_id The identifier for the application.
  # @param replace_logout_redirect_urls_request Callback details.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'replace_logout_redirect_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replace_redirect_callback_urls
  # Replace Redirect Callback URLs
  # Replace all redirect callback URLs.
  # @param app_id The identifier for the application.
  # @param replace_redirect_callback_urls_request Callback details.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'replace_redirect_callback_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
