=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::FeatureFlagsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FeatureFlagsApi' do
  before do
    # run before each test
    @api_instance = KindeApi::FeatureFlagsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FeatureFlagsApi' do
    it 'should create an instance of FeatureFlagsApi' do
      expect(@api_instance).to be_instance_of(KindeApi::FeatureFlagsApi)
    end
  end

  # unit tests for create_feature_flag
  # Create a new feature flag
  # Create feature flag.
  # @param name The name of the flag.
  # @param description Description of the flag purpose.
  # @param key The flag identifier to use in code.
  # @param type The variable type.
  # @param allow_override_level Allow the flag to be overridden at a different level.
  # @param default_value Default value for the flag used by environments and organizations.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'create_feature_flag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_feature_flag
  # Delete a feature flag
  # Delete feature flag
  # @param feature_flag_key The identifier for the feature flag.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'delete_feature_flag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_feature_flag
  # Update a feature flag
  # Update feature flag.
  # @param feature_flag_key The key identifier for the feature flag.
  # @param name The name of the flag.
  # @param description Description of the flag purpose.
  # @param type The variable type
  # @param allow_override_level Allow the flag to be overridden at a different level.
  # @param default_value Default value for the flag used by environments and organizations.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'update_feature_flag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
