=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::PermissionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PermissionsApi' do
  before do
    # run before each test
    @api_instance = KindeApi::PermissionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PermissionsApi' do
    it 'should create an instance of PermissionsApi' do
      expect(@api_instance).to be_instance_of(KindeApi::PermissionsApi)
    end
  end

  # unit tests for create_permission
  # Create Permission
  # Create a new permission.
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePermissionRequest] :create_permission_request Permission details.
  # @return [SuccessResponse]
  describe 'create_permission test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_permission
  # Delete Permission
  # Delete permission
  # @param permission_id The identifier for the permission.
  # @param [Hash] opts the optional parameters
  # @return [SuccessResponse]
  describe 'delete_permission test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_permissions
  # List Permissions
  # The returned list can be sorted by permission name or permission ID in ascending or descending order. The number of records to return at a time can also be controlled using the &#x60;page_size&#x60; query string parameter. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field and order to sort the result by.
  # @option opts [Integer] :page_size Number of results per page. Defaults to 10 if parameter not sent.
  # @option opts [String] :next_token A string to get the next page of results if there are more results.
  # @return [GetPermissionsResponse]
  describe 'get_permissions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_permissions
  # Update Permission
  # Update permission
  # @param permission_id The identifier for the permission.
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePermissionRequest] :create_permission_request Permission details.
  # @return [SuccessResponse]
  describe 'update_permissions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
