=begin
#Kinde Management API

# Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::SelfServePortalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SelfServePortalApi' do
  before do
    # run before each test
    @api_instance = KindeApi::SelfServePortalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SelfServePortalApi' do
    it 'should create an instance of SelfServePortalApi' do
      expect(@api_instance).to be_instance_of(KindeApi::SelfServePortalApi)
    end
  end

  # unit tests for get_portal_link
  # Get self-serve portal link
  # Returns a link to the self-serve portal for the authenticated user. The user can use this link to manage their account, update their profile, and view their entitlements. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :subnav The area of the portal you want the user to land on
  # @option opts [String] :return_url The URL to redirect the user to after they have completed their actions in the portal.
  # @return [GetPortalLink]
  describe 'get_portal_link test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
