=begin
#Kinde Management API

# Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for KindeApi::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = KindeApi::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(KindeApi::WebhooksApi)
    end
  end

  # unit tests for create_web_hook
  # Create a Webhook
  # Create a webhook  &lt;div&gt;   &lt;code&gt;create:webhooks&lt;/code&gt; &lt;/div&gt; 
  # @param create_web_hook_request Webhook request specification.
  # @param [Hash] opts the optional parameters
  # @return [CreateWebhookResponse]
  describe 'create_web_hook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_web_hook
  # Delete Webhook
  # Delete webhook  &lt;div&gt;   &lt;code&gt;delete:webhooks&lt;/code&gt; &lt;/div&gt; 
  # @param webhook_id The webhook id.
  # @param [Hash] opts the optional parameters
  # @return [DeleteWebhookResponse]
  describe 'delete_web_hook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event
  # Get Event
  # Returns an event  &lt;div&gt;   &lt;code&gt;read:events&lt;/code&gt; &lt;/div&gt; 
  # @param event_id The event id.
  # @param [Hash] opts the optional parameters
  # @return [GetEventResponse]
  describe 'get_event test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_event_types
  # List Event Types
  # Returns a list event type definitions  &lt;div&gt;   &lt;code&gt;read:event_types&lt;/code&gt; &lt;/div&gt; 
  # @param [Hash] opts the optional parameters
  # @return [GetEventTypesResponse]
  describe 'get_event_types test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_web_hooks
  # List Webhooks
  # List webhooks  &lt;div&gt;   &lt;code&gt;read:webhooks&lt;/code&gt; &lt;/div&gt; 
  # @param [Hash] opts the optional parameters
  # @return [GetWebhooksResponse]
  describe 'get_web_hooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_web_hook
  # Update a Webhook
  # Update a webhook  &lt;div&gt;   &lt;code&gt;update:webhooks&lt;/code&gt; &lt;/div&gt; 
  # @param webhook_id The webhook id.
  # @param update_web_hook_request Update webhook request specification.
  # @param [Hash] opts the optional parameters
  # @return [UpdateWebhookResponse]
  describe 'update_web_hook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
