=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

# Common files
require 'kinde_sdk/api_client'
require 'kinde_sdk/api_error'
require 'kinde_sdk/version'
require 'kinde_sdk/configuration'

# Models
KindeSdk.autoload :AddOrganizationUsers200Response, 'kinde_sdk/models/add_organization_users200_response'
KindeSdk.autoload :AddOrganizationUsersRequest, 'kinde_sdk/models/add_organization_users_request'
KindeSdk.autoload :ApiResult, 'kinde_sdk/models/api_result'
KindeSdk.autoload :ConnectedAppsAccessToken, 'kinde_sdk/models/connected_apps_access_token'
KindeSdk.autoload :ConnectedAppsAuthUrl, 'kinde_sdk/models/connected_apps_auth_url'
KindeSdk.autoload :CreateOrganizationRequest, 'kinde_sdk/models/create_organization_request'
KindeSdk.autoload :CreateUser200Response, 'kinde_sdk/models/create_user200_response'
KindeSdk.autoload :CreateUserRequest, 'kinde_sdk/models/create_user_request'
KindeSdk.autoload :CreateUserRequestIdentitiesInner, 'kinde_sdk/models/create_user_request_identities_inner'
KindeSdk.autoload :CreateUserRequestIdentitiesInnerDetails, 'kinde_sdk/models/create_user_request_identities_inner_details'
KindeSdk.autoload :CreateUserRequestProfile, 'kinde_sdk/models/create_user_request_profile'
KindeSdk.autoload :Error, 'kinde_sdk/models/error'
KindeSdk.autoload :ErrorResponse, 'kinde_sdk/models/error_response'
KindeSdk.autoload :GetOrgainzations200Response, 'kinde_sdk/models/get_orgainzations200_response'
KindeSdk.autoload :GetOrganizationUsers200Response, 'kinde_sdk/models/get_organization_users200_response'
KindeSdk.autoload :GetUsers200Response, 'kinde_sdk/models/get_users200_response'
KindeSdk.autoload :Organization, 'kinde_sdk/models/organization'
KindeSdk.autoload :OrganizationUser, 'kinde_sdk/models/organization_user'
KindeSdk.autoload :RemoveOrganizationUsers200Response, 'kinde_sdk/models/remove_organization_users200_response'
KindeSdk.autoload :RemoveOrganizationUsersRequest, 'kinde_sdk/models/remove_organization_users_request'
KindeSdk.autoload :SuccessResponse, 'kinde_sdk/models/success_response'
KindeSdk.autoload :UpdateUserRequest, 'kinde_sdk/models/update_user_request'
KindeSdk.autoload :User, 'kinde_sdk/models/user'
KindeSdk.autoload :UserIdentity, 'kinde_sdk/models/user_identity'
KindeSdk.autoload :UserIdentityResult, 'kinde_sdk/models/user_identity_result'
KindeSdk.autoload :UserProfile, 'kinde_sdk/models/user_profile'
KindeSdk.autoload :UserProfileV2, 'kinde_sdk/models/user_profile_v2'

# APIs
KindeSdk.autoload :ConnectedAppsApi, 'kinde_sdk/api/connected_apps_api'
KindeSdk.autoload :EnvironmentsApi, 'kinde_sdk/api/environments_api'
KindeSdk.autoload :FeatureFlagsApi, 'kinde_sdk/api/feature_flags_api'
KindeSdk.autoload :OAuthApi, 'kinde_sdk/api/o_auth_api'
KindeSdk.autoload :OrganizationsApi, 'kinde_sdk/api/organizations_api'
KindeSdk.autoload :UsersApi, 'kinde_sdk/api/users_api'

module KindeSdk
  class << self
    # Customize default settings for the SDK using block.
    #   KindeSdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
