=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KindeSdk::ConnectedAppsAccessToken
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KindeSdk::ConnectedAppsAccessToken do
  let(:instance) { KindeSdk::ConnectedAppsAccessToken.new }

  describe 'test an instance of ConnectedAppsAccessToken' do
    it 'should create an instance of ConnectedAppsAccessToken' do
      expect(instance).to be_instance_of(KindeSdk::ConnectedAppsAccessToken)
    end
  end
  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "access_token_expiry"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
