=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 0.0.1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KindeSdk::CreateUserRequestIdentitiesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KindeSdk::CreateUserRequestIdentitiesInner do
  let(:instance) { KindeSdk::CreateUserRequestIdentitiesInner.new }

  describe 'test an instance of CreateUserRequestIdentitiesInner' do
    it 'should create an instance of CreateUserRequestIdentitiesInner' do
      expect(instance).to be_instance_of(KindeSdk::CreateUserRequestIdentitiesInner)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
