# frozen_string_literal: true

# #Kinde Management API
#
# Provides endpoints to manage your Kinde Businesses
#
# The version of the OpenAPI document: 1
# Contact: support@kinde.com
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 7.0.0-SNAPSHOT
#

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KindeApi::ConnectedAppsAuthUrl
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KindeApi::ConnectedAppsAuthUrl do
  let(:instance) { KindeApi::ConnectedAppsAuthUrl.new }

  describe 'test an instance of ConnectedAppsAuthUrl' do
    it 'should create an instance of ConnectedAppsAuthUrl' do
      expect(instance).to be_instance_of(KindeApi::ConnectedAppsAuthUrl)
    end
  end
  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "session_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
