=begin
#Kinde Management API

#Provides endpoints to manage your Kinde Businesses

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KindeApi::RedirectCallbackUrls
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KindeApi::RedirectCallbackUrls do
  let(:instance) { KindeApi::RedirectCallbackUrls.new }

  describe 'test an instance of RedirectCallbackUrls' do
    it 'should create an instance of RedirectCallbackUrls' do
      expect(instance).to be_instance_of(KindeApi::RedirectCallbackUrls)
    end
  end
  describe 'test attribute "redirect_urls"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
