=begin
#Kinde Management API

# Provides endpoints to manage your Kinde Businesses.  ## Intro  ## How to use  1. [Set up and authorize a machine-to-machine (M2M) application](https://docs.kinde.com/developer-tools/kinde-api/connect-to-kinde-api/).  2. [Generate a test access token](https://docs.kinde.com/developer-tools/kinde-api/access-token-for-api/)  3. Test request any endpoint using the test token 

The version of the OpenAPI document: 1
Contact: support@kinde.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KindeApi::SetUserPasswordRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe KindeApi::SetUserPasswordRequest do
  let(:instance) { KindeApi::SetUserPasswordRequest.new }

  describe 'test an instance of SetUserPasswordRequest' do
    it 'should create an instance of SetUserPasswordRequest' do
      expect(instance).to be_instance_of(KindeApi::SetUserPasswordRequest)
    end
  end
  describe 'test attribute "hashed_password"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hashing_method"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["bcrypt", "crypt", "md5", "wordpress"])
      # validator.allowable_values.each do |value|
      #   expect { instance.hashing_method = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "salt"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "salt_position"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["prefix", "suffix"])
      # validator.allowable_values.each do |value|
      #   expect { instance.salt_position = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "is_temporary_password"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
